- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: e8a3e305-3c9d-4f6f-b1f5-b20dad294a9e
  loglevel: INFO
  name: crawl-from-rundeck
  nodeFilterEditable: false
  schedule:
    dayofmonth:
      day: 1/1
    month: '*'
    time:
      hour: 0/1
      minute: '0'
      seconds: '0'
    year: '*'
  scheduleEnabled: true
  sequence:
    commands:
    - description: ハッピーメール
      exec: /home/tsu-nera/repo/auto-matching-reiwa/bin/crawl-from-rundeck-happymail.sh
    - description: ワクワクメール
      exec: /home/tsu-nera/repo/auto-matching-reiwa/bin/crawl-from-rundeck-wakuwaku.sh
    - description: PCMAX
      exec: /home/tsu-nera/repo/auto-matching-reiwa/bin/crawl-from-rundeck-pcmax.sh
    - description: イククル
      exec: /home/tsu-nera/repo/auto-matching-reiwa/bin/crawl-from-rundeck-ikukuru.sh
    keepgoing: true
    strategy: sequential
  uuid: e8a3e305-3c9d-4f6f-b1f5-b20dad294a9e
